### Reading an image using cv2.imread() with flag cv2.IMREAD_COLOR

In [1]:
# pip install opencv-python

In [2]:
#Import cv2 library after install opencv-python 
import cv2
import numpy as np
import os
os.chdir('E:\\prasad\\SMIIT\\Opencv\\OpenCV-Reading-Writing-and-Displaying-Images') # for change Directory

In [3]:
# Read the given image
img=cv2.imread('22.jpg',cv2.IMREAD_COLOR)
# OR
# img=cv2.imread('22.jpg',1)

In [4]:
img.shape

(704, 564, 3)

In [5]:
print(img)

[[[ 95 139 203]
  [119 163 227]
  [105 148 211]
  ...
  [ 86  94 123]
  [ 87  95 124]
  [ 86  94 123]]

 [[ 89 133 197]
  [121 165 229]
  [109 152 215]
  ...
  [ 86  94 123]
  [ 88  96 125]
  [ 87  95 124]]

 [[ 84 128 192]
  [122 166 230]
  [108 151 214]
  ...
  [ 87  96 123]
  [ 88  97 124]
  [ 88  97 124]]

 ...

 [[121 164 207]
  [124 166 209]
  [117 153 199]
  ...
  [ 62  78  60]
  [ 63  79  61]
  [ 64  80  62]]

 [[125 168 211]
  [118 160 203]
  [115 151 197]
  ...
  [ 65  81  63]
  [ 66  82  64]
  [ 67  83  65]]

 [[131 174 217]
  [109 151 194]
  [101 137 183]
  ...
  [ 67  83  65]
  [ 68  84  66]
  [ 69  85  67]]]


In [6]:
type(img)

numpy.ndarray

In [7]:
print(img.max())
print(img.min())

255
0


## Display Color image using cv2.imshow()

In [8]:
# Display Color image using cv2.imshow()
cv2.imshow('Girl',img)

#wait to close window
cv2.waitKey(0)

#close all windows
cv2.destroyAllWindows()

### Reading an image using cv2.imread() with flag cv2.IMREAD_GRAYSCALE

In [9]:
# Read the given image
img1=cv2.imread('22.jpg',cv2.IMREAD_GRAYSCALE)
# OR
# img=cv2.imread('22.jpg',0)

In [10]:
img1.shape

(704, 564)

In [11]:
print(img1)

[[153 177 162 ... 102 103 102]
 [147 179 166 ... 102 104 103]
 [142 180 165 ... 103 104 104]
 ...
 [172 174 163 ...  71  72  73]
 [176 168 161 ...  74  75  76]
 [182 159 147 ...  76  77  78]]


In [12]:
img1.size

397056

In [13]:
type(img1)

numpy.ndarray

## Display this gray scale image

In [14]:
cv2.imshow('Girl_Gray',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Let's take a closer look at how images are stored

In [15]:
# Check Shape of Image
# first value is basically Height-704, second value is width-564 and third value is channels-3. 
# 3-means COLOR image RGB.
# If image is black and white that time showing only 1 channels 
print(img.shape)

(704, 564, 3)


In [16]:
# Let's print each dimension of the image
print('Height of the image: ',img.shape[0],'pixels')  #Check Shape of Image index[0]

Height of the image:  704 pixels


In [17]:
img.shape[1]  #Check Shape of Image index[1]
print('Width of the image: ',img.shape[1],'pixels')  #Check Shape of Image index[1]

Width of the image:  564 pixels


In [18]:
print('Channels of the image: ',img.shape[2],'Channels')  #Check channel of Image index[2]

Channels of the image:  3 Channels


## Saving or Writing image: cv2.imwrite()

In [19]:
# Simply use 'imwrite' specificing the file name and the image to be saved
cv2.imwrite('output.jpg',img)  # Save image in current location

True

## Resize Image

In [20]:
# Read the given image
img=cv2.imread('27.jpg')

In [21]:
# Resize Image
img=cv2.resize(img,(1080,720))

#show Image
cv2.imshow('Car',img)

#wait to close window
cv2.waitKey(0)

#close all windows
cv2.destroyAllWindows()

## Image Frame

In [22]:
# Read the given image
img=cv2.imread('24.jpg')

In [23]:
# Resize Image
img=cv2.resize(img,(200,200))

# Adding images horizontally and Vertically
img2=np.hstack((img,img,img,img,)) # Same image add 4 times horizontally

img4=np.vstack((img2,img2,img2)) # horizontaly image add 3 times Vertically

cv2.imshow('Cute_Girl',img4) # Show images

cv2.waitKey(0) #wait to close window

cv2.destroyAllWindows() #close all windows

# Thank You!